accounts:
  - name: khidi
    coins: ["20000token", "200000000stake"]
  - name: hyunchang
    coins: ["10000token", "100000000stake"]
validator:
  name: khidi
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: hyunchang
  coins: ["5token", "100000stake"]
