// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: khidi/hy_partner.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HyPartner struct {
	Index      string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Buyer      string `protobuf:"bytes,2,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller     string `protobuf:"bytes,3,opt,name=seller,proto3" json:"seller,omitempty"`
	Year       string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Proportion string `protobuf:"bytes,5,opt,name=proportion,proto3" json:"proportion,omitempty"`
}

func (m *HyPartner) Reset()         { *m = HyPartner{} }
func (m *HyPartner) String() string { return proto.CompactTextString(m) }
func (*HyPartner) ProtoMessage()    {}
func (*HyPartner) Descriptor() ([]byte, []int) {
	return fileDescriptor_91496cc301240947, []int{0}
}
func (m *HyPartner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HyPartner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HyPartner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HyPartner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HyPartner.Merge(m, src)
}
func (m *HyPartner) XXX_Size() int {
	return m.Size()
}
func (m *HyPartner) XXX_DiscardUnknown() {
	xxx_messageInfo_HyPartner.DiscardUnknown(m)
}

var xxx_messageInfo_HyPartner proto.InternalMessageInfo

func (m *HyPartner) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *HyPartner) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *HyPartner) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *HyPartner) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *HyPartner) GetProportion() string {
	if m != nil {
		return m.Proportion
	}
	return ""
}

func init() {
	proto.RegisterType((*HyPartner)(nil), "khidi.khidi.HyPartner")
}

func init() { proto.RegisterFile("khidi/hy_partner.proto", fileDescriptor_91496cc301240947) }

var fileDescriptor_91496cc301240947 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xce, 0xc8, 0x4c,
	0xc9, 0xd4, 0xcf, 0xa8, 0x8c, 0x2f, 0x48, 0x2c, 0x2a, 0xc9, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x8b, 0xeb, 0x81, 0x49, 0xa5, 0x66, 0x46, 0x2e, 0x4e, 0x8f, 0xca,
	0x00, 0x88, 0x02, 0x21, 0x11, 0x2e, 0xd6, 0xcc, 0xbc, 0x94, 0xd4, 0x0a, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x08, 0x07, 0x24, 0x9a, 0x54, 0x5a, 0x99, 0x5a, 0x24, 0xc1, 0x04, 0x11, 0x05,
	0x73, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x53, 0x73, 0x72, 0x52, 0x8b, 0x24, 0x98, 0xc1, 0xc2, 0x50,
	0x9e, 0x90, 0x10, 0x17, 0x4b, 0x65, 0x6a, 0x62, 0x91, 0x04, 0x0b, 0x58, 0x14, 0xcc, 0x16, 0x92,
	0xe3, 0xe2, 0x2a, 0x28, 0xca, 0x2f, 0xc8, 0x2f, 0x2a, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x05, 0xcb,
	0x20, 0x89, 0x38, 0xe9, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72,
	0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x30,
	0xc4, 0x13, 0x15, 0xfa, 0x10, 0xba, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x11, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xd9, 0x6c, 0x32, 0xe2, 0x00, 0x00, 0x00,
}

func (m *HyPartner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HyPartner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HyPartner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proportion) > 0 {
		i -= len(m.Proportion)
		copy(dAtA[i:], m.Proportion)
		i = encodeVarintHyPartner(dAtA, i, uint64(len(m.Proportion)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Year) > 0 {
		i -= len(m.Year)
		copy(dAtA[i:], m.Year)
		i = encodeVarintHyPartner(dAtA, i, uint64(len(m.Year)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintHyPartner(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintHyPartner(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintHyPartner(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHyPartner(dAtA []byte, offset int, v uint64) int {
	offset -= sovHyPartner(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HyPartner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovHyPartner(uint64(l))
	}
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovHyPartner(uint64(l))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovHyPartner(uint64(l))
	}
	l = len(m.Year)
	if l > 0 {
		n += 1 + l + sovHyPartner(uint64(l))
	}
	l = len(m.Proportion)
	if l > 0 {
		n += 1 + l + sovHyPartner(uint64(l))
	}
	return n
}

func sovHyPartner(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHyPartner(x uint64) (n int) {
	return sovHyPartner(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HyPartner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHyPartner
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HyPartner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HyPartner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyPartner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyPartner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyPartner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyPartner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyPartner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyPartner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Year", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyPartner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyPartner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Year = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proportion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHyPartner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHyPartner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proportion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHyPartner(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHyPartner
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHyPartner(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHyPartner
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHyPartner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHyPartner
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHyPartner
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHyPartner
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHyPartner        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHyPartner          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHyPartner = fmt.Errorf("proto: unexpected end of group")
)
